ktor:
  deployment:
    port:
  application:
    modules:
      - github.mixexsu.HttpKt.configureHttp
      - github.mixexsu.SerializationKt.configureSerialization
      - github.mixexsu.SecurityKt.configureSecurity
      - github.mixexsu.ExposedKt.configureExposed
      - github.mixexsu.PostgresKt.configurePostgres
      - github.mixexsu.RoutingKt.configureRouting
